info:
  artifactid: @project.artifactId@
  version: @project.version@

spring:
  application:
    name: configservice

server:
  port: 8888

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/

---

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///home/darek/Devel/Workspace/Spring/spring-io-lab6-config
