info:
  artifactid: @project.artifactId@
  version: @project.version@

spring:
  application:
    name: configservice

server:
  port: 8888

---

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///home/darek/Devel/Workspace/Spring/spring-io-lab6-config
